# Generated by Django 5.1.6 on 2025-07-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text='Agent matricule number', max_length=20, unique=True)),
                ('nom', models.CharField(help_text='Agent last name', max_length=100)),
                ('prenom', models.CharField(blank=True, help_text='Agent first name', max_length=100, null=True)),
                ('nom_complet', models.CharField(blank=True, help_text='Full name as in Excel', max_length=200, null=True)),
                ('affectation', models.CharField(blank=True, help_text='Agent affectation/assignment', max_length=100, null=True)),
                ('periode', models.CharField(blank=True, help_text='Period information', max_length=200, null=True)),
                ('source_file', models.CharField(help_text='Source Excel file name', max_length=200)),
                ('status', models.CharField(blank=True, help_text='Status (ok, etc.)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['matricule'],
            },
        ),
    ]
