# Generated by Django 5.1.6 on 2025-07-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age en 2024', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='date_naissance',
            field=models.DateField(blank=True, help_text='Date de naissance', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='formation',
            field=models.TextField(blank=True, help_text='Formation reçue', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='sheet_name',
            field=models.CharField(blank=True, help_text='Nom de la feuille Excel', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='periode',
            field=models.CharField(blank=True, help_text='Période de formation', max_length=200, null=True),
        ),
    ]
