# Generated by Django 5.1.6 on 2025-07-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_age_agent_date_naissance_agent_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='affectation_unite',
            field=models.CharField(blank=True, help_text='Affectation unité', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='anciennete',
            field=models.IntegerField(blank=True, help_text='Ancienneté en années', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='date_fonction_actuelle',
            field=models.DateField(blank=True, help_text='Date fonction actuelle', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='date_fonction_administrative',
            field=models.DateField(blank=True, help_text='Date fonction administrative', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='date_recrutement',
            field=models.DateField(blank=True, help_text='Date de recrutement', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='fonction_actuelle',
            field=models.CharField(blank=True, help_text='Fonction actuelle', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='fonction_administration',
            field=models.CharField(blank=True, help_text="Fonction d'administration", max_length=200, null=True),
        ),
    ]
