# Generated by Django 5.1.6 on 2025-07-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_affectation_unite_agent_anciennete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='fonction_grade',
            field=models.CharField(blank=True, help_text='Fonction ou grade', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name (alias)', max_length=200, null=True),
        ),
    ]
