# Generated by Django 5.1.6 on 2025-07-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_fonction_grade_agent_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='date_fonction_administrative',
        ),
        migrations.AddField(
            model_name='agent',
            name='date_affectation_unite',
            field=models.DateField(blank=True, help_text='Date affectation unité', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='date_fonction_administration',
            field=models.DateField(blank=True, help_text='Date fonction administration', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='date_fonction_technique_actuelle',
            field=models.DateField(blank=True, help_text='Date fonction technique actuelle', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='fonction_technique_actuelle',
            field=models.CharField(blank=True, help_text='Fonction technique actuelle', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='formation_autre',
            field=models.CharField(blank=True, help_text="Autre formation (si 'Autre' sélectionné)", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='formation',
            field=models.CharField(blank=True, choices=[('formation_base', 'Formation de base'), ('ab_initio', 'Ab initio'), ('formation_gestion_equipe', "Formation gestion d'équipe"), ('formation_formateur', 'Formation des formateurs'), ('formation_leadership', 'Formation leadership'), ('autre', 'Autre')], help_text='Type de formation reçue', max_length=50, null=True),
        ),
    ]
