# Generated by Django 5.1.6 on 2025-07-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_remove_agent_date_fonction_administrative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='formation',
            field=models.CharField(blank=True, help_text='Type de formation reçue', max_length=200, null=True),
        ),
    ]
